name: SocialJax_yml
channels:
  - conda-forge
dependencies:
  - python=3.10

  # framework
  - cuda-version=11.8
  - cudatoolkit=11.8
  - jaxlib=0.4.23=*cuda*
  - jax=0.4.23

  # SocialJax deps
  - flax==0.7.4
  - scipy==1.12.0
  - distrax==0.1.5
  - safetensors==0.5.2
  - hydra-core==1.3.2
  - wandb==0.18.5

  - pip
  - pip:
    - gymnax==0.0.8
